apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  name: desc-dilema6
spec:
  name: desc-dilema6
  maxSessionDuration: 3600
  path: /
  policies:
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Service": "ec2.amazonaws.com"
          },
          "Action": "sts:AssumeRole"
        }
      ]
    }